Previously, in Lab 3, we learned how to use some ML models in scikit learn package on a regression task with some data preprocessing procedures. This week, we are going to review the data preprocessing procedures and apply logistic regression as well as support vector machine (SVM) on a classification task.

Task

This database is collected from the V.A. Medical Center, Long Beach and Cleveland Clinic Foundation. It contains information from 303 patients,  with 14 attributes (13 input variables and 1 target variable). 

We are using this dataet to Build a machine learning model to predict if a patiet presents heart disease. The detailed information of each variable is as follows:
1. age: age in years
2. sex (male and female)
3. chest pain type
4. resting blood pressure (in mm Hg on admission to the hospital)
5. serum cholestoral in mg/dl
6. fasting blood sugar > 120 mg/dl (true and false)
7. resting electrocardiographic results
<br>   -- Value 0: normal
<br>   -- Value 1: having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of > 0.05 mV)
<br>   -- Value 2: showing probable or definite left ventricular hypertrophy by Estes' criteria
8. maximum heart rate achieved
9. exang: exercise induced angina (1 = yes; 0 = no)
10. oldpeak = ST depression induced by exercise relative to rest
11. slope: the slope of the peak exercise ST segment
<br>   -- Value 1: upsloping
<br>   -- Value 2: flat
<br>   -- Value 3: downsloping
12. number of major vessels (0-3) colored by flourosopy
13. thal: 3 = normal; 6 = fixed defect; 7 = reversable defect
14. num: diagnosis of heart disease (angiographic disease status)
<br>   -- Value 0: absense
<br>   -- Value 1: presence

more information of the dataset can be found here: https://archive.ics.uci.edu/ml/datasets/Heart+Disease

### Load the dataset
use pandas to load the csv file "heart_disease.csv" provided on LMS, then check dataset length and print the first 5 rows of the dataset

In [76]:
import pandas as pd

df = pd.read_csv("heart_disease.csv")

df.head()

Age     Sex   Chest Pain Type  Resting Blood Pressure  Serum Cholestoral  \
0   63    male    typical angina                     145                233   
1   67    male      asymptomatic                     160                286   
2   67    male      asymptomatic                     120                229   
3   37    male  non-anginal pain                     130                250   
4   41  female   atypical angina                     130                204   

   Fasting Blood Sugar  Resting electrocardiographic results  \
0                 True                                     2   
1                False                                     2   
2                False                                     2   
3                False                                     0   
4                False                                     2   

   Maximum heart rate achieved  Exercise induced angina  ST depression  \
0                          150                        0            2.3   
1                          108                        1            1.5   
2                          129                        1            2.6   
3                          187                        0            3.5   
4                          172                        0            1.4   

   the slope  Number of major vessels  thal  Diagnosis  
0          3                      0.0   6.0          0  
1          2                      3.0   3.0          1  
2          2                      2.0   7.0          1  
3          3                      0.0   3.0          0  
4          1                      0.0   3.0          0

### Preprocess the dataset
##### Check if there is any missing value in the dataset

In [77]:
import numpy as np

totalmiss = df.isnull().sum()
totalmiss

Age                                     0
Sex                                     0
Chest Pain Type                         0
Resting Blood Pressure                  0
Serum Cholestoral                       0
Fasting Blood Sugar                     0
Resting electrocardiographic results    0
Maximum heart rate achieved             0
Exercise induced angina                 0
ST depression                           0
the slope                               0
Number of major vessels                 4
thal                                    2
Diagnosis                               0
dtype: int64

##### Drop the rows which has missing values

In [78]:
df = df.dropna()

df.isnull().sum()

Age                                     0
Sex                                     0
Chest Pain Type                         0
Resting Blood Pressure                  0
Serum Cholestoral                       0
Fasting Blood Sugar                     0
Resting electrocardiographic results    0
Maximum heart rate achieved             0
Exercise induced angina                 0
ST depression                           0
the slope                               0
Number of major vessels                 0
thal                                    0
Diagnosis                               0
dtype: int64

##### Check variable data types

In [79]:
df.dtypes

Age                                       int64
Sex                                      object
Chest Pain Type                          object
Resting Blood Pressure                    int64
Serum Cholestoral                         int64
Fasting Blood Sugar                        bool
Resting electrocardiographic results      int64
Maximum heart rate achieved               int64
Exercise induced angina                   int64
ST depression                           float64
the slope                                 int64
Number of major vessels                 float64
thal                                    float64
Diagnosis                                 int64
dtype: object

We found that Number of major vessels and thal should be int but is presented as float, so we transform them into integer type

In [80]:
cols = ['Number of major vessels', 'thal']
df[cols] = df[cols].astype(int)

In [81]:
# check again
df.dtypes

Age                                       int64
Sex                                      object
Chest Pain Type                          object
Resting Blood Pressure                    int64
Serum Cholestoral                         int64
Fasting Blood Sugar                        bool
Resting electrocardiographic results      int64
Maximum heart rate achieved               int64
Exercise induced angina                   int64
ST depression                           float64
the slope                                 int64
Number of major vessels                   int32
thal                                      int32
Diagnosis                                 int64
dtype: object

We can see that these two variables are properly transformed now

##### Check if there is any duplicated rows in the dataset

In [82]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
297    False
298    False
299    False
300    False
301    False
Length: 297, dtype: bool

##### check value count for the categorical variables

In [83]:
print(df['Sex'].value_counts())
print(df['Chest Pain Type'].value_counts())
print(df['Fasting Blood Sugar'].value_counts())
print(df['Resting electrocardiographic results'].value_counts())
print(df['Exercise induced angina'].value_counts())
print(df['the slope'].value_counts())
print(df['thal'].value_counts())


male      201
female     96
Name: Sex, dtype: int64
asymptomatic        142
non-anginal pain     83
atypical angina      49
typical angina       23
Name: Chest Pain Type, dtype: int64
False    254
True      43
Name: Fasting Blood Sugar, dtype: int64
0    147
2    146
1      4
Name: Resting electrocardiographic results, dtype: int64
0    200
1     97
Name: Exercise induced angina, dtype: int64
1    139
2    137
3     21
Name: the slope, dtype: int64
3    164
7    115
6     18
Name: thal, dtype: int64


##### Deal with categorical variables

Since both Sex and Fasting Blook Sugar are binary variables, we can also use 0 and 1 to replace them.

for example, for variable Sex:
<br> 1 = male; 0 = female

for variable Fasting Blood Sugar:
<br> 1 = True; 0 = False

In addition, based on domain expert's advice, we can use the following rule to transform the categorical variable Chest Pain Type:
<br>-- Value 1: typical angina
<br>-- Value 2: atypical angina
<br>-- Value 3: non-anginal pain
<br>-- Value 4: asymptomatic

In [84]:
df['Sex'] = df['Sex'].apply(lambda x : 1 if x == 'male' else 0)
df['Fasting Blood Sugar'] = df['Fasting Blood Sugar'].apply(lambda x : 1 if x == True else 0)
df['Chest Pain Type'] = df['Chest Pain Type'].replace({'typical angina': 1, 'atypical angina': 2, 'non-anginal pain': 3, 'asymptomatic': 4})

In [85]:
df.head()

Age  Sex  Chest Pain Type  Resting Blood Pressure  Serum Cholestoral  \
0   63    1                1                     145                233   
1   67    1                4                     160                286   
2   67    1                4                     120                229   
3   37    1                3                     130                250   
4   41    0                2                     130                204   

   Fasting Blood Sugar  Resting electrocardiographic results  \
0                    1                                     2   
1                    0                                     2   
2                    0                                     2   
3                    0                                     0   
4                    0                                     2   

   Maximum heart rate achieved  Exercise induced angina  ST depression  \
0                          150                        0            2.3   
1                          108                        1            1.5   
2                          129                        1            2.6   
3                          187                        0            3.5   
4                          172                        0            1.4   

   the slope  Number of major vessels  thal  Diagnosis  
0          3                        0     6          0  
1          2                        3     3          1  
2          2                        2     7          1  
3          3                        0     3          0  
4          1                        0     3          0

##### Check dataset shape

In [86]:
df.shape

(297, 14)

##### Define the input variables and the target variable
target variable is the last variable Diagnosis, and input variables are the rest of the columns.

In [87]:
x = np.array(df.drop(['Diagnosis'], 1))
y = np.array(df['Diagnosis'])

print(x)
print(y)

[[63.  1.  1. ...  3.  0.  6.]
 [67.  1.  4. ...  2.  3.  3.]
 [67.  1.  4. ...  2.  2.  7.]
 ...
 [68.  1.  4. ...  2.  2.  7.]
 [57.  1.  4. ...  2.  1.  7.]
 [57.  0.  2. ...  2.  1.  3.]]
[0 1 1 0 0 0 1 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 1 1 1 0 0 0 0 1 0 1 1 0 0 0 1
 1 1 0 1 0 0 0 1 1 0 1 0 0 0 0 1 0 1 1 1 1 0 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1
 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 1 0 1 1 1 1 1 1
 0 1 1 0 0 0 1 1 1 1 0 1 1 0 1 1 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0 1 0 1 1 0 0
 0 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0 0 0 1 0 1 0 1 0 1 1 0 1 0 0 1 1 0 0 1 0 0
 1 1 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 1 1 1 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1
 0 0 0 1 1 0 1 1 0 0 1 1 1 0 0 0 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 0 0 1 0 1
 0 0 1 1 1 1 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 1 1 1 0 0 1 0 1 1 1 0 1 1 1 1 1
 1]


C:\Users\edwar\AppData\Local\Temp\ipykernel_19004\1520630228.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x = np.array(df.drop(['Diagnosis'], 1))


### Split the dataset and normalize data

##### Split the training and testing dataset
use 10% of dataset for testing with a random state of 1

In [88]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.1, random_state=1)


##### Apply normalization on both train and testing dataset

In [89]:
from sklearn.preprocessing import MinMaxScaler

norm = MinMaxScaler().fit(x_train)
x_train_norm = norm.transform(x_train)
x_test_norm = norm.transform(x_test)

### Now we are learning how to train a model with logistic regression and SVM for classification, based on entire training dataset and then evaluate the model based on testing dataset
Be aware that, for regression model, the default evaluation metrics is R Squared. For regression task, the default evaluation metrics is accuracy

In [90]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

# logistic regression model, parameters can be changed
lr = LogisticRegression(solver="liblinear")
lr.fit(x_train, y_train)
test_score = lr.score(x_test, y_test)
print("Testing Accuracy of LR:", test_score)

# Support Vector Machine for classification, parameters can be changed
svm = SVC()
svm.fit(x_train, y_train)
test_score = svm.score(x_test, y_test)
print("Testing Accuracy of SVC:", test_score)

Testing Accuracy of LR: 0.9333333333333333
Testing Accuracy of SVC: 0.6333333333333333


### Train a model with 5-fold cross valiation

##### Define a 5 fold cross validation with data shufflling and set the random state with 2

In [91]:
from sklearn.model_selection import KFold, cross_val_score

kfold = KFold(n_splits=5, shuffle=True, random_state=2)

##### Run the 5-fold cross validation and print the average accuracy score based on the cross validation results, and evaluate both model on the testing dataset

In [92]:
lr = LogisticRegression()
svm = SVC()
lrresults = cross_val_score(lr, x_test_norm, y_test, cv=kfold)
svmresults = cross_val_score(svm, x_test_norm, y_test, cv=kfold)

print(lrresults.mean())
print(svmresults.mean())

0.8333333333333334
0.7666666666666667


### Optimize the Logistic Regression models with cross validation
The parameters that can be applied in grid_params can be found here: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html You can add values and parameters in the grid_params_lr.

In [93]:
# fine tune parameters for lr model
from sklearn.model_selection import GridSearchCV

grid_params_lr = {
    'penalty': ['l1', 'l2'],
    'C': [1, 10],
    'solver': ['saga', 'liblinear']
}

lr = LogisticRegression(max_iter=150)
gs_lr_result = GridSearchCV(lr, grid_params_lr, cv=kfold).fit(x_train_norm, y_train)
print(f"{gs_lr_result.best_score_:.3f}")

0.846


### Evaluate the trained Logistic Regression model using testing dataset

In [94]:
test = gs_lr_result.best_estimator_.score(x_test_norm, y_test)
print(f"{test:.3f}")

0.967


check the parameter setting for the best selected model

In [95]:
gs_lr_result.best_params_

{'C': 1, 'penalty': 'l2', 'solver': 'liblinear'}

### Optimize the SVM models with the same steps
Parameters for SVM model can be found here: https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html

Evaluate the trained Logistic Regression model using testing dataset

In [96]:
# fine tune parameters for lr model
from sklearn.model_selection import GridSearchCV

grid_params_svm = {
    'C': [0.1, 1, 10, 100, 1000],  
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 
    'kernel': ['rbf']
}

svm = SVC()
gs_svm_result = GridSearchCV(svm, grid_params_svm, cv=kfold).fit(x_train_norm, y_train)
print(f"{gs_svm_result.best_score_:.3f}")

0.846


check the parameter setting for the best selected model

In [97]:
test1 = gs_svm_result.best_estimator_.score(x_test_norm, y_test)
print(f"{test1:.3f}")

0.833


In [98]:
gs_svm_result.best_params_

{'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}